const countries=['TW','JP','PH','ID','SG'];let live={};let scenario=false;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tabPage').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
function fmtTime(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function project(lon,lat){const minLon=117,maxLon=124,minLat=20,maxLat=27;return [((lon-minLon)/(maxLon-minLon))*960,620-((lat-minLat)/(maxLat-minLat))*620]}
function drawGrid(){const g=$('.gridlines');for(let i=1;i<8;i++){let x=i*120,y=i*77.5;g.insertAdjacentHTML('beforeend',`<line x1="${x}" y1="0" x2="${x}" y2="620"/><line x1="0" y1="${y}" x2="960" y2="${y}"/>`)}}
function fallback(){const g=$('#fallbackCables');const paths=['M0 260 C180 250 310 290 456 310','M0 385 C175 360 300 405 443 420','M535 200 C670 160 820 145 960 110','M520 240 C700 260 790 320 960 340','M452 455 C620 500 805 520 960 565'];g.innerHTML=paths.map(d=>`<path class="fallbackCable" d="${d}"/>`).join('')}
async function loadOSM(){const q='[out:json][timeout:20];way["communication"="line"]["location"="underwater"](20,117,27,124);out geom;';try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',body:q,headers:{'Content-Type':'application/x-www-form-urlencoded'}});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();const ways=d.elements.filter(x=>x.geometry?.length>1);$('#cableCount').textContent=ways.length;$('#cableSourceState').textContent=ways.length?'live OpenStreetMap query':'no mapped objects returned';const g=$('#osmCables');g.innerHTML='';ways.slice(0,150).forEach(w=>{let pts=w.geometry.map(p=>project(p.lon,p.lat));let d='M '+pts.map(p=>p.join(' ')).join(' L ');g.insertAdjacentHTML('beforeend',`<path class="mapCable" d="${d}"><title>${w.tags?.name||w.tags?.operator||'OpenStreetMap submarine telecom line'}</title></path>`)});if(ways.length){$('#fallbackCables').style.display='none';$('#mapNotice').textContent=`Loaded ${ways.length} public underwater telecom line object(s) from OpenStreetMap. This is topology data, not operator fault telemetry.`}else throw new Error('No mapped cable objects in query area')}catch(e){fallback();$('#cableCount').textContent='demo';$('#cableSourceState').textContent='OSM layer unavailable';$('#mapNotice').textContent='OpenStreetMap cable query is unavailable or incomplete; showing fallback topology while live Internet measurements remain active.'}}
async function probeCountry(cc){const u=`https://atlas.ripe.net/api/v2/probes/?country_code=${cc}&page_size=100&format=json`;const r=await fetch(u);if(!r.ok)throw new Error(cc);const d=await r.json();const rows=d.results||[];return {cc,count:d.count,connected:rows.filter(x=>x.status?.id===1||x.status?.name==='Connected').length,sample:rows.slice(0,12)}}
async function loadProbes(){try{const arr=await Promise.all(countries.map(probeCountry));live=Object.fromEntries(arr.map(x=>[x.cc,x]));const tw=live.TW;$('#twCount').textContent=tw.count;$('#twConnected').textContent=`${tw.connected} connected in first API page`;$('#regionConnected').textContent=arr.reduce((a,x)=>a+x.connected,0);const max=Math.max(...arr.map(x=>x.connected),1);$('#countryBars').innerHTML=arr.map(x=>`<div class="barRow"><b>${x.cc}</b><div class="bar"><i style="width:${x.connected/max*100}%"></i></div><b>${x.connected}</b></div>`).join('');$('#probeTable').innerHTML=tw.sample.map(p=>`<div class="probeRow"><b>#${p.id}</b><span>${p.description||'RIPE Atlas probe'}</span><span>AS${p.asn_v4||'—'}</span><span>${p.status?.name||'unknown'}</span></div>`).join('');drawProbeDots(tw.sample);$('#syncState').textContent='LIVE DATA ONLINE'}catch(e){$('#syncState').textContent='PARTIAL / RETRY';$('#twConnected').textContent='live API unavailable'}$('#lastSync').textContent=fmtTime()}
function drawProbeDots(rows){const g=$('#probeLayer');g.innerHTML='';rows.filter(p=>p.geometry?.coordinates).forEach(p=>{const [lon,lat]=p.geometry.coordinates;if(lon<117||lon>124||lat<20||lat>27)return;const [x,y]=project(lon,lat);g.insertAdjacentHTML('beforeend',`<circle class="probeDot" cx="${x}" cy="${y}" r="4"><title>RIPE Atlas #${p.id} • AS${p.asn_v4||'?'}</title></circle>`)})}
function toggleScenario(){scenario=!scenario;let g=$('#osmCables');if(scenario){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.id='scenarioOverlay';p.setAttribute('class','scenarioLine');p.setAttribute('d','M455 414 C300 395 160 360 0 370');$('#map').appendChild(p);$('#scenarioTitle').textContent='Southwest international-link disruption';$('#scenarioText').textContent='Hypothetical scenario only: compare southwest-path disruption assumptions with live RIPE Atlas reachability and later BGP indicators.';$('#resilienceScore').textContent='72 / 100'}else{$('#scenarioOverlay')?.remove();$('#scenarioTitle').textContent='No scenario active';$('#scenarioText').textContent='Use the scenario control to model a hypothetical international-link disruption and compare it with live public network measurements.';$('#resilienceScore').textContent='—'}}
$('#scenarioBtn').onclick=toggleScenario;$('#reloadData').onclick=()=>{loadOSM();loadProbes()};drawGrid();fallback();loadOSM();loadProbes();